CREATE TABLE transactions (
`id`					  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id`				  INT(10) UNSIGNED NOT NULL,
`code`					  smallint(5) NOT NULL,
`title`					  varchar(255) NOT NULL,
`caller`				  varchar(100) NULL DEFAULT NULL,
`type`				      ENUM('gift','prize','transfer', 'promo', 'money') NOT NULL,
`unit_id`				  smallint(3) NOT NULL,
`date`				  	  date NOT NULL,
`time`				  	  TIME NOT NULL,
`amount_request`		  BIGINT(20) NULL DEFAULT NULL,
`amount_end`			  BIGINT(20) NULL DEFAULT NULL,
`plus`					  BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`minus`					  BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`budget_before`			  BIGINT(20) NULL DEFAULT NULL,
`budget`				  BIGINT(20) NULL DEFAULT NULL,
`status`				  ENUM('enable','disable','deleted','expired','awaiting','filtered','blocked','spam') NOT NULL DEFAULT 'enable',
`condition`				  ENUM('request','redirect','cancel','pending','error','verify_request','verify_error','ok') NULL DEFAULT NULL,
`verify`			      bit(1) NOT NULL DEFAULT 0,
`parent_id`				  BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`related_user_id`		  INT(10) UNSIGNED NULL DEFAULT NULL,
`related_foreign`		  varchar(50) NULL DEFAULT NULL,
`related_id`			  BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`payment`				  varchar(50) NULL DEFAULT NULL,
`payment_response`		  text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
`meta`					  mediumtext  CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`desc`					  text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
`createdate`			  datetime DEFAULT CURRENT_TIMESTAMP,
`date_modified`			  timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
CONSTRAINT `newtransactions_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;